import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { UserPlus, Upload } from 'lucide-react';
import Input from '../common/Input.jsx';
import Button from '../common/Button.jsx';

const INITIAL_FORM = {
  companyName: '',
  name: '',
  email: '',
  phone: '',
  password: '',
  confirmPassword: '',
};

export default function SignupForm() {
  const navigate = useNavigate();
  const [form, setForm] = useState(INITIAL_FORM);
  const [isLoading, setIsLoading] = useState(false);

  function handleChange(e) {
    setForm((prev) => ({ ...prev, [e.target.name]: e.target.value }));
  }

  function handleSubmit(e) {
    e.preventDefault();
    // NOTE: demo-only flow. Replace with authService.signup(form).
    // Per product spec: the Login ID is auto-generated by the system as
    // [Company Code][First 2 letters of first+last name][Year of joining][Serial no.]
    setIsLoading(true);
    setTimeout(() => {
      setIsLoading(false);
      navigate('/login');
    }, 400);
  }

  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-5" noValidate>
      <p className="rounded-lg bg-primary-50 px-3.5 py-2.5 text-xs text-primary-600">
        New employee accounts are created by an HR Officer or Admin. The login ID and
        initial password are generated automatically by the system.
      </p>

      <div className="flex items-end gap-3">
        <Input
          label="Company Name"
          name="companyName"
          value={form.companyName}
          onChange={handleChange}
          containerClassName="flex-1"
          required
        />
        <Button type="button" variant="secondary" icon={Upload} aria-label="Upload logo">
          Logo
        </Button>
      </div>

      <Input label="Full Name" name="name" value={form.name} onChange={handleChange} required />
      <Input label="Email" name="email" type="email" autoComplete="email" value={form.email} onChange={handleChange} required />
      <Input label="Phone" name="phone" type="tel" value={form.phone} onChange={handleChange} required />

      <div className="grid grid-cols-2 gap-4">
        <Input
          label="Password"
          name="password"
          type="password"
          autoComplete="new-password"
          value={form.password}
          onChange={handleChange}
          required
        />
        <Input
          label="Confirm Password"
          name="confirmPassword"
          type="password"
          autoComplete="new-password"
          value={form.confirmPassword}
          onChange={handleChange}
          required
        />
      </div>

      <Button type="submit" icon={UserPlus} isLoading={isLoading} fullWidth>
        Sign Up
      </Button>
      <p className="text-center text-xs text-text-secondary">
        Already have an account?{' '}
        <Link to="/login" className="font-medium text-primary hover:underline">
          Sign In
        </Link>
      </p>
    </form>
  );
}
